### ISSUE TITLE
Short roadmap for a first fit with theory uncertainties

### ISSUE THREAD

**Issue by scarrazza** [NNPDF/nnpdf#292]
Lets summarize here the steps discussed in Milan in order to obtain a first prototype fit with theory uncertainties:

- [x] Measure time required for loading & generating MC replicas (RK)
- [x] Perform a 3.1 fit with a single experiment (MW, TG)
- [x] Conclude the th-covmat related actions in `vp-setupfit` (#244 & #284)
- [x] Implement the C++ I/O in #284 
- [x] Adjust / test / merge / extend covmats following #279.
- [x] Perform first fit with th-covmat
