### ISSUE TITLE
Roadmap for experiment API

### ISSUE THREAD

**Issue by scarrazza** [NNPDF/nnpdf#483]
Following the discussion in #476 the next steps require at least:

**Integration with validphys**
- [ ] replace `CommonData` object calls with the new dataframe
- [ ] implement conversion mapping between `experiments` and the new `data` key.

**New features**
- [ ] implement filtering
- [ ] implement artificial replica generation
- [ ] implement covariance matrix computation
