### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by mariaubiali** [NNPDF/nnpdf#656]
Outstanding to-do-list 

Done

- [x]  Added a link to the docs in the wiki and substitute obsolete wiki pages with new pages on the official documentation @mariaubiali 
- [x] Add list of Git repos to GitHub instructions @voisey
- [x] Add list of rules for the mailing lists to the doc pages @mariaubiali 
- [x] Add page on documentation on the documentation @siranipour 
- [x] Split up documentation on theory cov. matrix in different pages @RosalynLP 
- [x] Finalise page on how to generate APPLgrids @enocera 
Add missing tutorial pages:
- [x] how to compare PDF sets @voisey @siranipour 
- [x] how to get a list of available fits @voisey
- [x] how to generate a report @voisey @siranipour
- [x] how to run a fit @JesusUrtasun 
- [x] how to make code reviews @Zaharid 
- [x] n3fit
- [x] how code testing works in python @Zaharid 
- [x] Add a list of theories and theory specs @voisey
- [x] Postfit docs that include the selection criteria, how to change them, where they're recorded @voisey 
- [x] validphys --help @RosalynLP
- [x] Sort out structure of docs - add intros for sections explaining what's in there @RosalynLP @voisey #1121 #1122
- [x] Move section on filter to a independent section outside of vp-guide @siranipour (decided not to do this)
- [x] how to add new plotting functionalities in VP @RosalynLP
- [x] how to include theory covariance matrix in a fit @RosalynLP
- [x] How to plot PDFs @RosalynLP 
- [x] namespaces @RosalynLP
- [x] PLOTTING files @siranipour 
- [x] Positivity & integrability implementation in n3fit @tgiani 
- [x] Add links to validphys report tutorial @voisey
- [x] Fix search bar #1125 @RosalynLP 
- [x] reportengine @Zaharid 
- [x] The reportengine execution model @Zaharid 
- ~~[ ] libnnpdf (we want a light introduction) @wilsonmr~~
- [x] reportengine reports @Zaharid 
- [x] General introduction to the code/code layout

To do
- [ ] SWIG wrappers @Zaharid 
- [ ] Default settings for datasets (cfactors, *_SF datasets, etc.) @enocera
- [x] Paramfits module (see https://github.com/NNPDF/nnpdf/issues/266) @Zaharid

**Comment by scarlehoff** [comment]
> Hi @scarlehoff what about adding the group picture that we have on the NNPDF website

Which one? But yes, we could put it at the bottom under the names (so that the documentation is the first thing people see).

For the links,  we can also create an issue with a list and ask people if they are happy with the link / affiliation. @scarrazza Given that we need to update the zenodo-citation list of authors maybe it makes sense to do both in one go (the list of people in the documentation should be equal -or greater if we add people who left- to the list of people in zenodo)

**Comment by scarlehoff** [comment]
Closed as complete now although I still think the https://docs.nnpdf.science is a bit dry and maybe we should go back to the idea of putting a picture below the name.s..

**Comment by AleCandido** [comment]
> Closed as complete now although I still think the [docs.nnpdf.science](https://docs.nnpdf.science) is a bit dry and maybe we should go back to the idea of putting a picture below the name.s..

We should put profile pictures [for every tutorial](https://pennylane.ai/qml/demos/tutorial_qubit_rotation.html#about-the-author) and [thumbs up/down](https://reactjs.org/tutorial/tutorial.html#wrapping-up) buttons on pages :P
